apiVersion: v1
kind: Secret
metadata:
  name: platform-secret
  namespace: multi-tenant
type: Opaque
stringData:
  JWT_SECRET: change-me
  MASTER_DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/master_db
